spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 5KB
      max-file-size: 20MB
      max-request-size: 35MB

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus
  endpoint:
    health:
      show-details: ALWAYS
      probes:
        enabled: true

siga:
  client:
    hmac:
      algorithm: HmacSHA256
